/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(conv_encoder_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(35f67fb9be3d5e7885fe485409c796c0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dab/conv_encoder_bb.h>
// pydoc.h is automatically generated in the build directory
#include <conv_encoder_bb_pydoc.h>

void bind_conv_encoder_bb(py::module& m)
{

    using conv_encoder_bb = ::gr::dab::conv_encoder_bb;


    py::class_<conv_encoder_bb,
               gr::block,
               gr::basic_block,
               std::shared_ptr<conv_encoder_bb>>(m, "conv_encoder_bb", D(conv_encoder_bb))

        .def(py::init(&conv_encoder_bb::make),
             py::arg("framesize"),
             D(conv_encoder_bb, make))


        ;
}
