/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dab_transmission_frame_mux_bb.h) */
/* BINDTOOL_HEADER_FILE_HASH(2b7ed00ad0e8a5b6e34ce8b05188da35)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dab/dab_transmission_frame_mux_bb.h>
// pydoc.h is automatically generated in the build directory
#include <dab_transmission_frame_mux_bb_pydoc.h>

void bind_dab_transmission_frame_mux_bb(py::module& m)
{

    using dab_transmission_frame_mux_bb = ::gr::dab::dab_transmission_frame_mux_bb;


    py::class_<dab_transmission_frame_mux_bb,
               gr::block,
               gr::basic_block,
               std::shared_ptr<dab_transmission_frame_mux_bb>>(
        m, "dab_transmission_frame_mux_bb", D(dab_transmission_frame_mux_bb))

        .def(py::init(&dab_transmission_frame_mux_bb::make),
             py::arg("transmission_mode"),
             py::arg("num_subch"),
             py::arg("subch_size"),
             D(dab_transmission_frame_mux_bb, make))


        ;
}
