/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(demux_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(cc33467d822ab6d49c3ae29439d351cf)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dab/demux_cc.h>
// pydoc.h is automatically generated in the build directory
#include <demux_cc_pydoc.h>

void bind_demux_cc(py::module& m)
{

    using demux_cc = ::gr::dab::demux_cc;


    py::class_<demux_cc, gr::block, gr::basic_block, std::shared_ptr<demux_cc>>(
        m, "demux_cc", D(demux_cc))

        .def(py::init(&demux_cc::make),
             py::arg("symbol_length"),
             py::arg("symbols_fic"),
             py::arg("symbol_msc"),
             py::arg("fillval") = ::gr_complex(0, 0),
             D(demux_cc, make))


        ;
}
