/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mp4_encode_sb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f3c5297954f45e7e7f6af024777caee1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dab/mp4_encode_sb.h>
// pydoc.h is automatically generated in the build directory
#include <mp4_encode_sb_pydoc.h>

void bind_mp4_encode_sb(py::module& m)
{

    using mp4_encode_sb = ::gr::dab::mp4_encode_sb;


    py::class_<mp4_encode_sb, gr::block, gr::basic_block, std::shared_ptr<mp4_encode_sb>>(
        m, "mp4_encode_sb", D(mp4_encode_sb))

        .def(py::init(&mp4_encode_sb::make),
             py::arg("bit_rate_n"),
             py::arg("channels"),
             py::arg("samp_rate"),
             py::arg("afterburner"),
             D(mp4_encode_sb, make))


        ;
}
