/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ofdm_coarse_frequency_correction_vcvc.h) */
/* BINDTOOL_HEADER_FILE_HASH(99946608a411cc5c43b608dbd5988225)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dab/ofdm_coarse_frequency_correction_vcvc.h>
// pydoc.h is automatically generated in the build directory
#include <ofdm_coarse_frequency_correction_vcvc_pydoc.h>

void bind_ofdm_coarse_frequency_correction_vcvc(py::module& m)
{

    using ofdm_coarse_frequency_correction_vcvc =
        ::gr::dab::ofdm_coarse_frequency_correction_vcvc;


    py::class_<ofdm_coarse_frequency_correction_vcvc,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ofdm_coarse_frequency_correction_vcvc>>(
        m,
        "ofdm_coarse_frequency_correction_vcvc",
        D(ofdm_coarse_frequency_correction_vcvc))

        .def(py::init(&ofdm_coarse_frequency_correction_vcvc::make),
             py::arg("fft_length"),
             py::arg("num_carriers"),
             py::arg("cyclic_prefix_length"),
             D(ofdm_coarse_frequency_correction_vcvc, make))


        .def("get_snr",
             &ofdm_coarse_frequency_correction_vcvc::get_snr,
             D(ofdm_coarse_frequency_correction_vcvc, get_snr))


        ;
}
