/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(qpsk_mapper_vbvc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a3179101c9c5c1af064059e46312631e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dab/qpsk_mapper_vbvc.h>
// pydoc.h is automatically generated in the build directory
#include <qpsk_mapper_vbvc_pydoc.h>

void bind_qpsk_mapper_vbvc(py::module& m)
{

    using qpsk_mapper_vbvc = ::gr::dab::qpsk_mapper_vbvc;


    py::class_<qpsk_mapper_vbvc,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<qpsk_mapper_vbvc>>(
        m, "qpsk_mapper_vbvc", D(qpsk_mapper_vbvc))

        .def(py::init(&qpsk_mapper_vbvc::make),
             py::arg("symbol_length"),
             D(qpsk_mapper_vbvc, make))


        ;
}
