/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(select_cus_vfvf.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6b8f1e58a0de6a141f245302da309aea)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dab/select_cus_vfvf.h>
// pydoc.h is automatically generated in the build directory
#include <select_cus_vfvf_pydoc.h>

void bind_select_cus_vfvf(py::module& m)
{

    using select_cus_vfvf = ::gr::dab::select_cus_vfvf;


    py::class_<select_cus_vfvf,
               gr::block,
               gr::basic_block,
               std::shared_ptr<select_cus_vfvf>>(m, "select_cus_vfvf", D(select_cus_vfvf))

        .def(py::init(&select_cus_vfvf::make),
             py::arg("vlen"),
             py::arg("frame_len"),
             py::arg("address"),
             py::arg("size"),
             D(select_cus_vfvf, make))


        ;
}
