/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(time_interleave_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(54dd7bcffa614bc3b9f8640dc90d53f3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dab/time_interleave_bb.h>
// pydoc.h is automatically generated in the build directory
#include <time_interleave_bb_pydoc.h>

void bind_time_interleave_bb(py::module& m)
{

    using time_interleave_bb = ::gr::dab::time_interleave_bb;


    py::class_<time_interleave_bb,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<time_interleave_bb>>(
        m, "time_interleave_bb", D(time_interleave_bb))

        .def(py::init(&time_interleave_bb::make),
             py::arg("vector_length"),
             py::arg("scrambling_vector"),
             D(time_interleave_bb, make))


        ;
}
